#!/usr/bin/env python
"""Apply every resistance table to every accepted tile; write rasters, manifest, stats, gallery.

Outputs under <out>/resistance/<table_id>/<tile_id>.tif (band 1 resistance float32, band 2
nodata uint8 as float32 0/1) plus <out>/resistance.parquet (one row per tile × table with stats
and provenance) and docs/figures/<prefix>_resistance_gallery.png.

Usage: python scripts/build_resistance.py --tiles data/tiles/pilot --tables configs/resistance_tables \
           --out data/tiles/pilot --random-seed 20260905 --figure docs/figures/pilot_resistance_gallery.png
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib

import numpy as np
import pandas as pd
import rasterio
import yaml

from ecoflowbench.landscapes.real import read_tile
from ecoflowbench.resistance import apply_table, load_tables, perturb_table


def write_random_table(tables: dict, seed: int, table_dir: pathlib.Path) -> None:
    """Materialise the random table as a versioned YAML so it is reviewable and reproducible."""
    name = f"random_lm_{seed}"
    path = table_dir / f"{name}.yaml"
    if path.exists():
        return
    t = perturb_table(tables["large_mammal"], seed=seed, log_sd=0.5, table_id=name)
    d = t.model_dump()
    d["citations"] = ["Derived: log-normal (sd 0.5) perturbation of large_mammal v1; see random field for provenance"]
    header = ("# random_lm — randomly perturbed copy of large_mammal (brief §5 item 5) to decorrelate surrogates\n"
              f"# from any single expert table. Generated by scripts/build_resistance.py with seed {seed};\n"
              "# regenerate with ecoflowbench.resistance.perturb_table(large_mammal, seed, log_sd=0.5).\n")
    path.write_text(header + yaml.safe_dump(d, sort_keys=False))
    print("wrote", path)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tiles", required=True)
    ap.add_argument("--tables", default="configs/resistance_tables")
    ap.add_argument("--out", required=True)
    ap.add_argument("--random-seed", type=int, default=20260905)
    ap.add_argument("--figure", default=None)
    args = ap.parse_args()
    tdir = pathlib.Path(args.tables)
    tables = load_tables(tdir)
    write_random_table(tables, args.random_seed, tdir)
    tables = load_tables(tdir)
    tiles_root = pathlib.Path(args.tiles)
    out = pathlib.Path(args.out)
    df = pd.read_parquet(tiles_root / "tiles.parquet")
    df = df[df["qc_accept"]].reset_index(drop=True)
    rows = []
    examples = {}
    for _, row in df.iterrows():
        cov, tags = read_tile(str(tiles_root / row["path"]))
        with rasterio.open(tiles_root / row["path"]) as src:
            profile = src.profile
        for tid, t in tables.items():
            r, nd, stats = apply_table(t, cov)
            p = out / "resistance" / tid / f"{row['tile_id']}.tif"
            p.parent.mkdir(parents=True, exist_ok=True)
            prof = dict(profile, count=2, dtype="float32", nodata=None, compress="deflate", predictor=2)
            with rasterio.open(p, "w", **prof) as dst:
                dst.write(r, 1)
                dst.write(nd.astype(np.float32), 2)
                dst.set_band_description(1, "resistance")
                dst.set_band_description(2, "nodata_mask")
                dst.update_tags(tile_id=row["tile_id"], table_id=tid, table_version=t.version,
                                table_sha256=t.sha256 or "", r_max=t.r_max)
            rows.append({"tile_id": row["tile_id"], "table_id": tid, "table_version": t.version,
                         "table_sha256": t.sha256, "path": str(p.relative_to(out)), **stats,
                         "created_utc": dt.datetime.now(dt.UTC).isoformat(timespec="seconds")})
            if row["tile_id"] not in examples and len(examples) < 4:
                examples[row["tile_id"]] = {}
            if row["tile_id"] in examples:
                examples[row["tile_id"]][tid] = (r, nd)
    res = pd.DataFrame(rows)
    res.to_parquet(out / "resistance.parquet", index=False)
    summ = res.groupby("table_id")[["r_min", "r_max_obs", "r_median", "frac_nodata", "frac_at_rmax", "log10_contrast"]].agg(["mean", "max"])
    print(f"{len(res)} rasters ({df.shape[0]} tiles x {len(tables)} tables)")
    print(summ.round(3).to_string())
    (out / "resistance_summary.json").write_text(json.dumps(
        {tid: g[["r_min", "r_max_obs", "r_median", "frac_nodata", "frac_at_rmax", "log10_contrast"]].describe().to_dict()
         for tid, g in res.groupby("table_id")}, indent=1, default=float))
    if args.figure:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        tids = list(tables)
        fig, axes = plt.subplots(len(examples), len(tids) + 1, figsize=(2.3 * (len(tids) + 1), 2.4 * len(examples)))
        for i, (tile_id, d) in enumerate(examples.items()):
            cov, _ = read_tile(str(tiles_root / df.set_index("tile_id").loc[tile_id, "path"]))
            axes[i, 0].imshow(cov["landcover"], cmap="tab20", interpolation="nearest")
            axes[i, 0].set_title("landcover" if i == 0 else "", fontsize=8)
            axes[i, 0].set_ylabel(tile_id, fontsize=7)
            for j, tid in enumerate(tids, start=1):
                r, nd = d[tid]
                img = np.ma.masked_array(np.log10(r), nd)
                axes[i, j].imshow(img, cmap="magma", vmin=0, vmax=np.log10(tables[tid].r_max), interpolation="nearest")
                if i == 0:
                    axes[i, j].set_title(f"{tid}\nlog10 R, max {tables[tid].r_max:g}", fontsize=7)
            for ax in axes[i]:
                ax.set_xticks([])
                ax.set_yticks([])
        fig.tight_layout()
        fig.savefig(args.figure, dpi=90)
        print("wrote", args.figure)


if __name__ == "__main__":
    main()
