#!/usr/bin/env python
"""Assemble docs/phase_05_report.md from the build indexes and the analysis JSON files.

Runs analyze_build.py and budget_extrapolation.py logic inline (imports their outputs) so the report's
numbers are always regenerated from data. Usage:
    python scripts/write_phase05_report.py --builds data/builds/mini data/builds/probe_M ... --out docs/phase_05_report.md
"""
from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parents[1]


def run(cmd: list[str]) -> str:
    return subprocess.run(cmd, capture_output=True, text=True, check=True, cwd=ROOT).stdout


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--builds", nargs="+", required=True)
    ap.add_argument("--out", default="docs/phase_05_report.md")
    ap.add_argument("--status", action="store_true", help="also write docs/status/latest.md and append history")
    args = ap.parse_args()
    py = sys.executable
    analysis = run([py, "scripts/analyze_build.py", "--builds", *args.builds, "--out", "docs/figures", "--prefix", "phase05"])
    scale = ["--omniscape-scale", "XL=0.265,XXL=0.258"]   # adopted blocks 33 / 65 vs measured 17 / 33: (17/33)^2, (33/65)^2
    budget4 = run([py, "scripts/budget_extrapolation.py", "--builds", *args.builds, "--target-cpu-hours", "500", "--cpus-per-job", "4", *scale])
    budget1 = run([py, "scripts/budget_extrapolation.py", "--builds", *args.builds, "--target-cpu-hours", "500", "--cpus-per-job", "1",
                   "--out", "docs/figures/phase05_budget_1core.json", *scale])
    cmp_path = ROOT / "data/builds/mini/stats/solver_comparison.json"
    cmp = json.load(open(cmp_path))
    c = pd.DataFrame(cmp["compare"])
    det = pd.DataFrame(cmp["determinism"])
    mini = pd.read_parquet(ROOT / "data/builds/mini/index.parquet")
    man = pd.read_parquet(ROOT / "data/builds/mini/manifest.parquet")
    b4 = json.load(open(ROOT / "docs/figures/phase05_budget.json"))
    b1 = json.load(open(ROOT / "docs/figures/phase05_budget_1core.json"))
    one_core_total = f"{b1['proposed']['cpu_h']:,.0f} CPU-hours, {b1['proposed']['gb']:,.0f} GB"

    def num(col):
        v = pd.to_numeric(c[col], errors="coerce")
        return f"{v.max():.1e} (median {v.median():.1e})"

    def sect(text: str, title: str) -> str:
        i = text.find(title)
        j = text.find("\n### ", i + 1)
        body = text[i:j if j > 0 else None].strip().splitlines()
        body = [ln for ln in body[1:] if not ln.startswith("wrote ")]   # drop the inner header and log lines
        return "\n".join(body).strip()

    gens = man[man.family == "synthetic"].generator.value_counts().to_dict()
    tables = man[man.family == "real"].table_id.value_counts().to_dict()
    conv = {k: all(all(x) for x in c[k]) for k in ("pairwise_converged", "advanced_converged", "omniscape_converged")}
    tq = mini.groupby("kind").solve_time_s.describe()[["count", "50%", "mean", "max"]].round(3)
    flags = mini[mini.qc_flags != ""][["sample_id", "config", "generator", "resistance_table_id", "contrast", "qc_flags"]]
    xxl_note = "" if any("XXL" in b for b in args.builds) else "\n> XXL probe not yet included in the tables; see the status note.\n"
    report = f"""# Phase 5 report — solver pipeline and mini run (mandatory gate)

> **Superseded items (2026-09-06):** the cost-driven Omniscape blocks proposed below (XL 33, XXL 65) were
> tested for fidelity after this report and rejected; the adopted rule is block = largest odd ≤ radius/10
> (`docs/dataset_plan.md` §7, `DECISIONS.md`). The mini set described here was generated with the
> Phase-5 blocks and has been regenerated under the adopted rule (`data/builds/mini`, old set kept as
> `mini_phase5blocks`). Budget numbers in §6 are ICE-oriented and superseded by the plan's cost table.

Date: 2026-09-05. Status: **complete, STOPPED at the gate**; owner decisions needed before scaling (§9).
Same summary in `docs/status/latest.md`. All numbers below are regenerated by
`scripts/write_phase05_report.py` from the build indexes.

## 1. What was built

| Item | Location |
|---|---|
| Julia wrapper: `solve_pairwise` (T1/T1W/T1R/T2), `solve_advanced` (T3), `solve_omniscape` (T4), `SolveStats` (wall, max RSS, solver, precision, threads, versions, converged, error, fallback), exact-graph Kirchhoff residual at full precision, JIT warm-up, resumable `solve_shard` over HDF5 | `julia/AmpScapeSolve.jl/src/AmpScapeSolve.jl`, `scripts/solve_shard.jl` |
| Solver validation script (CHOLMOD vs CG+AMG, determinism) | `julia/AmpScapeSolve.jl/examples/solver_comparison.jl` |
| Python driver: manifest (UUID5 ids, shards), prepare (inputs HDF5), QC, finalize (final shard + Parquet index), quicklooks + contact sheet | `ampscape/solve/`, `scripts/generate.py` (plan / prepare / solve / submit / finalize / status) |
| Slurm array template (one shard per task, ≤ 4 h, no network, node-local `$TMPDIR`) | `scripts/slurm/solve_shard.sbatch` |
| Analysis: time/memory/storage tables, budget extrapolation, this report | `scripts/analyze_build.py`, `scripts/budget_extrapolation.py`, `scripts/write_phase05_report.py` |
| Builds on scratch | `data/builds/{{smoke5, mini, probe_M, probe_L, probe_XL, probe_XXL}}` |

Julia depot and precompiled cache live on scratch (`julia_depot/`); precompilation was run once, jobs only
load the cache and read prepared inputs (verified: the Slurm jobs ran with no network calls).

## 2. Solver configuration (verified against the installed Circuitscape.jl 5.17.1)

Recorded in every sample's `solver_params`: `scenario`, `solver` (cholmod), `precision` (double),
`connect_four_neighbors_only` (False), `connect_using_avg_resistances` (False = average conductance, explicit),
`habitat_map_is_resistances`, `use_polygons`, `ground_file_is_resistances` (False), `use_direct_grounds` (True),
`use_unit_currents` (False), `remove_src_or_gnd` (keepall), `use_64bit_indexing`, `parallelize` (False), plus the
hard-coded CG settings `cg_rtol_hardcoded = 1e-6`, `cg_itmax_hardcoded = 100000`, `accept_residual_hardcoded = 1e-4`
(from `src/core.jl`; **no INI key controls the CG tolerance**), `pair_convention` and `residual_rel`.
Omniscape: `radius`, `block_size`, `source_threshold`, `solver` (cholmod), `precision`, `correct_artifacts`,
`calc_flow_potential`, `calc_normalized_current`.

### 2.1 CHOLMOD vs CG+AMG on {cmp['n_compare']} mini samples (all configs, single thread)

| Quantity | max (median) relative difference |
|---|---|
| T1 cumulative current | {num('cum_current_reldiff')} |
| T2 effective resistance | {num('reff_reldiff')} |
| T3 current / voltage | {num('advanced_current_reldiff')} / {num('advanced_voltage_reldiff')} |
| T4 Omniscape cumulative current | {num('omniscape_cum_reldiff')} |

Converged with both solvers: pairwise {conv['pairwise_converged']}, advanced {conv['advanced_converged']},
omniscape {conv['omniscape_converged']}. Kirchhoff residual (full precision, exact graph): CHOLMOD
{min(x[0] for x in c.residual_cholmod if x[0] is not None):.0e}–{max(max(x) for x in c.residual_cholmod if x[0] is not None):.0e},
CG+AMG {min(x[0] for x in c.residual_cgamg if x[0] is not None):.0e}–{max(max(x) for x in c.residual_cgamg if x[0] is not None):.0e}.
Median wall time (s): pairwise {pd.Series([x[0] for x in c.t_pairwise]).median():.2f} (CHOLMOD) vs {pd.Series([x[1] for x in c.t_pairwise]).median():.2f} (CG+AMG);
advanced {pd.Series([x[0] for x in c.t_advanced]).median():.3f} vs {pd.Series([x[1] for x in c.t_advanced]).median():.3f};
omniscape {pd.Series([x[0] for x in c.t_omniscape]).median():.1f} vs {pd.Series([x[1] for x in c.t_omniscape]).median():.1f}.

**Conclusion:** CHOLMOD is exact to ~1e-12, as fast or faster, and — unlike CG+AMG — never aborts an
Omniscape solve (in the dev shard CG+AMG failed a whole T4 solve on a contrast-10⁴ landscape because one
window's residual exceeded Circuitscape's hard-coded 1e-4). CHOLMOD is the reference for all tasks;
CG+AMG remains the documented memory fallback (`fallback_solver` flag).

### 2.2 Determinism ({cmp['n_repeat']} samples solved twice per solver, `JULIA_NUM_THREADS=1`, BLAS threads 1)

| Solver | pairwise bitwise identical | Omniscape bitwise identical |
|---|---|---|
| CHOLMOD | {bool(det['pairwise_bitwise_cholmod'].all())} | {bool(det['omniscape_bitwise_cholmod'].all())} |
| CG+AMG | {bool(det['pairwise_bitwise_cg+amg'].all())} | {bool(det['omniscape_bitwise_cg+amg'].all())} |

Both are bitwise reproducible single-threaded. Production jobs use one Julia thread; CHOLMOD/BLAS get the
allocated cores (`OPENBLAS_NUM_THREADS = SLURM_CPUS_PER_TASK`), which we have not yet verified to be
bitwise stable across different core counts — the mini run (4 cores) is the reference machine setting.

## 3. Mini run

**Sampling.** 200 synthetic landscapes = seeds 20260905 … 20261104 drawn from the documented prior
(`DEFAULT_PRIOR`), which covers every generator: {gens}. 50 real = 10 tiles per resistance table
({tables}), one table per tile, all 5 tables. Every landscape gets: `points` (K ∈ [2, 8] → T1 + T2),
`wall_to_wall_NS` + `_EW` (T1W), `advanced` (T3), `omniscape` (T4); real tiles with ≥ 2 eligible habitat
patches also get `regions` (T1R). Total {len(mini)} configurations on {mini.sample_id.nunique()} samples.

**Execution.** 5-sample smoke build first (Slurm array of 2 tasks, both COMPLETED, 0 QC failures), then the
mini as `--array=0-4`, 50 samples per shard, 4 cores, 16 GB, 4 h limit: all 5 tasks COMPLETED in 10–12 min
wall each (~7.5–9 min solving + ~3.5 min Julia load/JIT). Resumable: `solve_shard` skips complete samples.

**Solve time per configuration (tier S, s):**

{tq.to_markdown()}

**QC.** qc_pass = {mini.qc_pass.mean():.4f}, qc_trainval = {mini.qc_trainval.mean():.4f}. Flags:

{flags.to_markdown(index=False) if len(flags) else 'none'}

All three `rmax_saturated` flags are the same contrast-10⁴ GRF landscape (> 50 % of pixels at r_max): kept
in the index, excluded from train/val per the owner rule. No sample failed convergence, finiteness,
all-zero, isolated-focal, conservation, or edge-artifact checks.

**Quicklooks.** One PNG per sample in `data/builds/mini/quicklooks/` (250 files, 52 MB, not committed);
contact sheet `docs/figures/mini_contact_sheet.png` (log R over cumulative current, first 60 samples).

## 4. Scaling probe (synthetic, `points` with K = 4 and `omniscape`, one sample per Julia process)

{sect(analysis, '### Solve time (s) and peak RSS')}

{sect(analysis, '### Wall time per sample')}

Peak RSS is the process high-water mark (`Sys.maxrss`), which includes ~1 GB of Julia/package baseline.
Figure: `docs/figures/phase05_solve_times.png`.
{xxl_note}
## 5. Storage per sample (compressed HDF5, gzip-4 + shuffle)

{sect(analysis, '### Storage')}

Pairwise maps for K ≤ 4 dominate (`voltage` + `pairwise_current` = 12 maps at K = 4).

## 6. Full-budget extrapolation

{sect(budget4, '### Measured median')}

{sect(budget4, '### Power-law')}

Omniscape scales super-linearly in pixels because the window size grows with the tier (radius ∝ size).
The XL and XXL Omniscape times in the budget tables are the measured values scaled to the **adopted**
block sizes (XL block 33 instead of the probed 17, XXL block 65 instead of 33; cost ∝ 1/block², i.e.
×0.265 and ×0.258); every other number is measured.

### 6.1 Brief's original ladder (§4.3), 4 cores per job

{sect(budget4, "### Brief's original ladder")}

### 6.2 Proposed ladder fitting ≈ 500 CPU-hours, 4 cores per job

{sect(budget4, '### Proposed ladder')}

### 6.3 The same 500 CPU-hours at 1 core per job ({one_core_total})

Tier-S/M solves are single-threaded in practice (33²–65² Omniscape windows, 16k–65k-node CHOLMOD), so
allocating 1 core per job should give the same wall time and 4× the samples per CPU-hour (to be
verified with one shard before adoption):

{sect(budget1, '### Proposed ladder')}

**Bottom line:** the brief's ladder costs ≈ {b4['brief']['cpu_h']:,.0f} CPU-hours (4 cores) and ≈ {b4['brief']['gb']:,.0f} GB;
T4 (Omniscape) is > 90 % of the compute at every tier. Levers, in order of impact: (a) solve T4 on a
subset of landscapes (e.g. 25 %), (b) 1-core jobs for S/M, (c) the larger XL/XXL block sizes already
adopted in `configs/solver/omniscape_reference.yaml`, (d) fewer XL/XXL samples.

## 7. QC exclusions

See §3: {int((~mini.qc_pass).sum())} hard failures; {int((~mini.qc_trainval).sum())} configurations excluded from train/val
(`rmax_saturated`), all retained in the index with the flag set.

## 8. Deviations / findings (all in `DECISIONS.md`)

- Omniscape reference solver = CHOLMOD (CG+AMG aborts whole solves on high-contrast windows).
- QC residual threshold 1e-6 instead of the brief's 1e-8: the double-precision floor for contrast-10⁴
  advanced systems is ≈ 1e-8 (observed 2.3e-8 with CHOLMOD); CG+AMG sits at 1e-6–3e-5, so 1e-6 still
  separates the solvers. The float32-recomputed residual is recorded but not a flag.
- Pair convention (node i grounded, 1 A at node j) and supernode residual for focal regions.
- JIT warm-up added after the first probe showed ~7 s of compile time inside single-sample jobs.
- XL Omniscape block 17 → 33 to keep solves under ~10 min; XXL provisional.
- `HF_ORG` still `Xirro`: the owner's placeholder "<correct name>" was not filled in.

## 9. Owner decisions needed at this gate

1. **Ladder and budget**: accept a ≈ 500 CPU-hour v1.0 (§6.2/6.3) or raise the budget; whether to solve
   T4 on a subset of landscapes; whether S/M jobs may use 1 core.
2. **HF storage** (deferred from Phase 2): free private quota 100 GB vs the ladder's storage.
3. **Omniscape XL/XXL windows**: confirm r128/b33 and r256/b65 (XXL measurement in status).
4. **HF_ORG**: the correct organisation name.
"""
    pathlib.Path(args.out).write_text(report)
    print("wrote", args.out)


if __name__ == "__main__":
    main()
